### ISSUE TITLE
Suggestion: open dropdown at top when don't have enough place

### ISSUE THREAD

**Issue by yeungc** [based-ghost/react-functional-select#10]
In some cases (ex: select language) we need to place the select at bottom of the page, would be great to open the dropdown at top when bottom don't have enough place.

For example if we removed the min-height of container in your storybook demo:
![0](https://user-images.githubusercontent.com/7931068/80836620-b8c8c500-8c27-11ea-9c32-9eb2f82d5d31.png)

**Comment by based-ghost** [comment]
@yeungc - agreed, I'll look into adding this. Now are you envisioning this as an "auto-detect" feature or more of an enum property where "menuPosition" could be expressed as "below" (default) or in this case, "above"?

**Comment by yeungc** [comment]
> 
> 
> @yeungc - agreed, I'll look into adding this. Now are you envisioning this as an "auto-detect" feature or more of an enum property where "menuPosition" could be expressed as "below" (default) or in this case, "above"?

Thank you, it's better to have the auto detect feature first, after that the menuPosition prop should be easy to implement :)

**Comment by based-ghost** [comment]
@yeungc - I released changes to address this issue under latest release of `v2.2.0`. There is a new property `menuPosition` which takes the value of `'top' | 'auto' | 'bottom'` and defaults to `'bottom'` to make sure existing functionality is maintained when upgrading. In your case, you could probably just pass `'top'`, since you know you want the menu to open above the control and using `'auto'` would make the component do a little extra work to calculate if it should place the menu above the control or not.

Let me know if this solves this issue or not - thanks!

**Comment by yeungc** [comment]
Yes it should cover most situation, thank you for the good work, I'm going to close the issue now!
