### ISSUE TITLE
I can't customize control container as much as I like

### ISSUE THREAD

**Issue by barkin94** [based-ghost/react-functional-select#16]
I've been having some issues with customization for the last couple of days. I tried and failed to do 2 things.

1) Give a custom height to the select container which is lower than its default value. I can change its font size by applying css to control container but i just cannot decrease the select container's default height. Is there a configuration option like `menuItemSize` that applies to the selector that I am potentially missing?

2) I need to apply custom style to the control box when the menu is toggled. The problem is clicking on the component focuses the select container instead of the control container so .rfs-control-container:focus doesn't get applied when the component is clicked. I tried the following scss rule but apparently it doesn't work either.
```
.rfs-select-container {
	&:focus {
		.rfs-control-container {
			background-color: #fff !important;
			box-shadow: 0 2.5px 5px 0 rgba(224, 228, 238, 0.75);
		}
	}
}

```
I'd appreciate some assistance.

**Comment by based-ghost** [comment]
Hey @barkin94 - you should be able to achieve your scenario after getting the latest version of `2.7.0`:

1). In previous versions you can achieve this, it just is difficult to see where the issue is - but on the `themeConfig.control` style object there are both `height` and `minHeight` properties - in your case, you would also need to set the `minHeight` to your desired height since it is less than the default of `38px`. However, in the latest version I am always setting the `minHeight` to the value of `height` when it is specified - more simple.

2). This is also achievable, but pretty messy - you could probably do this by updating the `themeConfig.control.css` property with a raw CSS string by passing callback funtions to the `onInputFocus` and `onInputBlur` properties. I just added the new css style property of `focusedCss` to `themeConfig.control` - which will just render any CSS passed when control is focused and remove when blurred.

Your solution will look something like this - passing this object to the `themeConfig` property (if using `styled-components` you can wrap `focusedCss`'s value with their `css` helper function:

```
{
  control: {
    height: '36px',
    focusedCss: 'background-color: #fff; box-shadow: 0 2.5px 5px 0 rgba(224, 228, 238, 0.75);'
  }
}

```

**Comment by barkin94** [comment]
Thanks. I managed to get it working. Tbh I would have preferred to apply these rules via css since I'm not familiar with styled components but hey at least it's working.

**Comment by based-ghost** [comment]
Ya - the issue with the focus functionality is that it is the invisible, deeply nested `<input>` element that is getting the focus so it can be interacted with - the focus is artificial to the control container. I guess one thing that could be done is when classNames is opted into and `isFocused === true`, a `is-focused` class could be appended to the control container.
