### ISSUE TITLE
AJAX/Fetch-powered dropdown?

### ISSUE THREAD

**Issue by paambaati** [based-ghost/react-functional-select#8]
I’m looking at the API, and I can’t figure out relevant options, but is it possible to build a dropdown that will fetch options via XHR/fetch as a user types input?

Of all the libraries I’ve explored, I love this one for a few reasons —

1. It is super lightweight.
2. It performs really well.
3. The API and the examples are all well laid out and thoughtful.

I’d absolutely love to use this library to build my dropdowns, but currently I’m looking for a component that will let me build a search-as-you-type dropdown.

**Comment by based-ghost** [comment]
Hey @paambaati thanks for the reminder for this - I have been meaning to add this feature for awhile now. I'm just running through some unit testing and should have a new version of the package released very shortly. I'll have a story new story named 'Async' added to the storybook of examples. I will comment again when it is ready to go, and you can let me know if it works out for you.

**Comment by based-ghost** [comment]
@paambaati the changes have been released under new version `v2.1.0` and documentation for the new async features can be found in the [Async Story](https://based-ghost.github.io/react-functional-select/?path=/story/react-functional-select--async). Let me know if you have any further questions or find some issues that I missed.

**Comment by paambaati** [comment]
@based-ghost Thanks for the amazing turnaround! I can’t wait to try this; if I can ask here, are there plans to support checkboxes in the dropdown?

**Comment by based-ghost** [comment]
I had not even thought about that case, but I don't think that would be too much work to add. I think most of it is almost there already if you use the `renderOptionLabel` property to render custom `JSX` for each option and set `closeMenuOnSelect` property to false to prevent the menu from closing from click around in the menu. However, there might be some work to do around linking the checked state of the boxes to the selected value. I'll play around with it in the near future since checkboxes or radio buttons are pretty commonly used in dropdowns.
